import json
import re

# Dictionnaire de traduction pour les noms de cartes
card_name_translations = {
    "목단 - 화중지왕": "Peony - King of Flowers",
    "크라운 - 영화": "Crown - Movie",
    "프리바티 - 샤프 레슨": "Privaty - Sharp Lesson",
    "홍련 : 흑영 - 연화": "Crimson Lotus: Black Shadow - Lotus Flower",
    "길티 - 디스빌리프 웨이브": "Guilty - Disbelief Wave",
    "사쿠라 : 블룸 인 서머": "Sakura: Bloom in Summer",
    "메어리 : 베이 갓데스": "Mary: Bay Goddess",
    "에이드 : 에이전트 바니": "Aide: Agent Bunny",
    "아니스 : 스타 - 스타라이트": "Anis: Star - Starlight",
    "스타 아니스": "Star Anis",
    "세븐스 드워프 풀 액티브": "Seventh Dwarf Full Active",
    "TRACING THE STARS": "TRACING THE STARS",
    "노른 코드 슈즈": "Norn Code Shoes",
    "티탄 매터 암가드": "Titan Matter Armguard",
    "마르차나 : 마린 스터디": "Marchana: Marine Study",
    "루주 - 언럭키 래빗": "Rouge - Unlucky Rabbit",
    "라피 : 레드 후드 - 샤인 라이트": "Rapi: Red Hood - Shine Light",
    "프리카": "Frica",
    "바이퍼 - 톡신 래빗": "Viper - Toxin Rabbit",
    "스노우 화이트 : 헤비암즈": "Snow White: Heavy Arms",
    "네온 : 비전 아이": "Neon: Vision Eye",
    "초화력": "Super Firepower",
    "노른 코드 고글": "Norn Code Goggle",
    "압도": "Overwhelm",
    "치얼업 투게더": "Cheer Up Together",
    "피날레": "Finale",
    "아군 합류": "Ally Join",
    "갓데시움 글러브": "Goddessium Glove",
    "와일드 투스": "Wild Tusk",
    "포메이션 F.F": "Formation F.F",
    "순백의 의지": "Pure White Will",
    "파란 나비의 꿈": "Blue Butterfly's Dream",
    "디저트 타임": "Dessert Time",
    "설온제": "Snow Warmth Festival",
    "VIP 기프트": "VIP Gift",
    "검신합일": "Sword God Unity",
    "갓데시움 프로텍터": "Goddessium Protector",
    "아틀라스 패턴 건틀렛": "Atlas Pattern Gauntlet",
    "신데렐라": "Cinderella",
    "에테르": "Ether",
    "미하라": "Mihara",
    "메이든 - 시크릿 너스": "Maiden - Secret Nurse",
    "시그널": "Signal",
    "애드미": "Admi",
    "유니 - 러블리 핑크": "Yuni - Lovely Pink",
    "엑시아 - 게이머즈": "Exia - Gamers",
    "율하": "Yulha",
    "노벨 - 펭귄 홈즈": "Novel - Penguin Holmes",
    "도라 - 다크 로즈": "Dora - Dark Rose",
    "퀀시": "Quency",
    "디젤 - 미드나잇 스트로베리": "Diesel - Midnight Strawberry",
    "루피": "Rupi",
    "얀 - 선라이즈 마켓": "Yan - Sunrise Market",
    "나가": "Naga",
    "티아": "Tia",
    "라푼젤": "Rapunzel",
    "브리드 - 블랙 문": "Brid - Black Moon",
    "솔린": "Solin",
    "클레이": "Clay",
    "볼륨": "Volume",
    "베이": "Bay",
    "아리아": "Aria",
    "엠마 - 달링 레드": "Emma - Darling Red",
    "자칼": "Jackal",
    "누아르 - 흑묘": "Noir - Black Cat",
    "블랑 - 백묘": "Blanc - White Cat",
    "바이퍼 - 샤인 오브 러브": "Viper - Shine of Love",
    "홍련": "Crimson Lotus",
    "레드 후드": "Red Hood",
    "라피 - 클래식 바캉스": "Rapi - Classic Vacances",
    "아니스 - 스파클링 서머": "Anis - Sparkling Summer",
    "루피 - 럭셔리 래빗": "Rupi - Luxury Rabbit",
    "퀀시 - 이스케이프 퀸": "Quency - Escape Queen",
    "모더니아 - 퍼스트 어펙션": "Modernia - First Affection",
    "그레이브": "Grave",
    "팬텀": "Phantom",
    "프리바티 - 거버먼트 노멀": "Privaty - Government Normal",
    "라이터즈 스포일러": "Writer's Spoiler",
    "신세계": "New World",
    "매터 타입 α 암가드": "Matter Type α Armguard",
    "헬름 - 아쿠아마린": "Helm - Aquamarine",
    "네베": "Neve",
    "키리": "Kiri",
    "에피넬": "Epinel",
    "하란": "Haran",
    "폴크방": "Folkvang",
    "앵커": "Anchor",
    "마스트 - 파이레츠 하트": "Mast - Pirate's Heart",
    "앨리스 - 원더랜드 바니": "Alice - Wonderland Bunny",
    "츠바이": "Zwei",
    "폴리": "Poli",
    "이사벨 - 허니문 파티": "Isabel - Honeymoon Party",
    "페퍼": "Pepper",
    "도로시 - 노스텔지어": "Dorothy - Nostalgia",
    "루드밀라 - 윈터 오너": "Ludmilla - Winter Owner",
    "루마니": "Rumani",
    "아인": "Ein",
    "메어리 - 베이 갓데스": "Mary - Bay Goddess",
    "트로니": "Troni",
    "슈가 - 콜 미 하드보일드": "Sugar - Call Me Hardboiled",
    "밀크": "Milk",
    "에이드": "Aid",
    "일레그": "Eleg",
    "코코아": "Cocoa",
    "프림 - 씨 오브 슬로스": "Prim - C of Sloth",
    "레오나": "Leona",
    "비스킷": "Biscuit",
    "라플라스": "Laplace",
    "네로": "Nero",
    "크라운 - 네이키드 킹": "Crown - Naked King",
    "리타 - 피쉬 가드": "Liter - Fish Guard",
    "드레이크 - 빌런 레이서": "Drake - Villain Racer",
    "센티 - 마이티 홀리데이": "Centi - Mighty Holiday",
    "소다 - 트윙클링 바니": "Soda - Twinkling Bunny",
    "맥스웰 - 메카닉 화이트": "Maxwell - Mechanic White",
    "용기있는 시선": "Brave Gaze",
    "비기너즈 베네핏": "Beginner's Benefit",
    "로얄 에타이어": "Royal Etayer",
    "고양이 보은": "Cat's Gratitude",
    "세라믹 고글": "Ceramic Goggle",
    "갓데시움 부츠": "Goddessium Boots",
    "아틀라스 패턴 프로텍터": "Atlas Pattern Protector",
    "패턴 시리즈 31 게이터": "Pattern Series 31 Gator",
    "베스티 - 아크 메이지": "Besty - Ark Mage",
    "노이즈 - 체리블로섬 스테이지": "Noise - Cherry Blossom Stage",
    "브래디": "Brady",
    "크러스트": "Crust",
    "꽃구경하지 않겠는가.": "Won't You View the Flowers?",
    "뉴 플레이버": "New Flavor",
    "폭발은 예술이다.": "Explosion is Art.",
    "계승되는 힘": "Inherited Power",
    "티탄 매터 바이저": "Titan Matter Visor",
    "티탄 매터 베스트": "Titan Matter Vest",
    "나가 - 라스트 걸후드": "Naga - Last Girlhood",
    "트리나": "Trina",
    "플로라": "Flora",
    "브리드 - 클래식 워커": "Brid - Classic Worker",
    "디젤 - 스트로베리 플라워": "Diesel - Strawberry Flower",
    "율리아 - 마일드 녹턴": "Julia - Mild Nocturne",
    "신 - 백스트리트 드림": "Shin - Backstreet Dream",
    "브랜드 뉴 이어": "Brand New Year",
    "최적의 경로": "Optimal Route",
    "축제의 끝": "End of Festival",
    "시크릿 가든": "Secret Garden",
    "레어 메탈 자켓": "Rare Metal Jacket",
    "레어 메탈 고글": "Rare Metal Goggle",
    "리틀 머메이드 - 어비스 플라워": "Little Mermaid - Abyss Flower",
    "로산나 - 시크 오션": "Rosanna - Chic Ocean",
    "니힐리스타": "Nihilista",
    "신데렐라 - 유리 공주": "Cinderella - Glass Princess",
    "사쿠라 - 흑야암행": "Sakura - Black Night Secret",
    "미하라 - 본딩 체인": "Mihara - Bonding Chain",
    "마나": "Mana",
    "메이든 - 언더 더 썬": "Maiden - Under the Sun",
    "D - 킬러 와이프": "D - Killer Wife",
    "킬 더 로드": "Kill the Lord",
    "M.M.R. 연구소": "M.M.R. Laboratory",
    "궤도 엘리베이터": "Orbital Elevator",
    "본딩 페인": "Bonding Pain",
    "갓데시움 베스트": "Goddessium Vest",
    "갓데시움 암가드": "Goddessium Armguard",
    "마스트 - 로망틱 메이드": "Mast - Romantic Maid",
    "앵커 - 이노센트 메이드": "Anchor - Innocent Maid",
    "헬름 - 애프터 샤워": "Helm - After Shower",
    "폴크방 - 모이스트 래빗": "Folkvang - Moist Rabbit",
    "페퍼 - 오션 비타민": "Pepper - Ocean Vitamin",
    "길로틴 - 윈터 슬레이어": "Guillotine - Winter Slayer",
    "매거진": "Magazine",
    "티탄 매터 부츠": "Titan Matter Boots",
    "아틀라스 패턴 건틀렛": "Atlas Pattern Gauntlet",
    "볼륨 - 비트 더 건": "Volume - Beat the Gun",
    "엠마 - 오피스 테라피": "Emma - Office Therapy",
    "레드 후드 - 넌센스 레드": "Red Hood - Nonsense Red",
    "라푼젤 - 퓨어 그레이스": "Rapunzel - Pure Grace",
    "마르차나 - 스쿨 데이즈": "Marchana - School Days",
    "티아 - 러블리 데이트": "Tia - Lovely Date",
    "딸기향 이끌림": "Strawberry Scent Attraction",
    "위대한 도둑": "Great Thief",
    "양호 선생님": "School Nurse",
    "아틀라스 패턴 헬멧": "Atlas Pattern Helmet",
    "메이든 - 아이스 로즈": "Maiden - Ice Rose",
    "폴리스 라인": "Police Line",
    "우리는 친구!.jpg": "We Are Friends!",
    "이지스 캐논 견제 사격": "Aegis Cannon Check Fire",
    "당근과 토끼 파티": "Carrot and Rabbit Party",
    "해적의 안목": "Pirate's Eye",
    "세라믹 베스트": "Ceramic Vest",
    "갓데시움 자켓": "Goddessium Jacket",
    "노른 코드 글러브": "Norn Code Glove",
    "패턴 시리즈 31 게이터": "Pattern Series 31 Gator",
}

# Traductions pour les termes de jeu
game_terms = {
    "트래시": "discard",
    "트래시 존": "discard zone",
    "대미지": "damage",
    "드로우": "draw",
    "파워": "power",
    "히트": "hit",
    "코스트": "cost",
    "레어도": "rarity",
    "소속": "affiliation",
    "효과": "effect",
    "유닛": "Unit",
    "리더": "Leader",
    "스킬": "Skill",
    "아이템": "Item",
    "화염": "Flame",
    "대지": "Earth",
    "파도": "Wave",
    "폭풍": "Storm",
    "번개": "Lightning",
    "어태커": "Attacker",
    "디펜더": "Defender",
    "가디언": "Guardian",
    "엔트리": "Entry",
    "엑시트": "Exit",
    "패시브": "Passive",
    "액티브": "Active",
    "광전사": "Radiant Warrior",
    "관통": "Pierce",
    "약탈": "Plunder",
    "희생": "Sacrifice",
    "종결": "Finish",
    "조우 유닛": "encounter unit",
    "필드": "field",
    "패": "hand",
    "덱": "deck",
    "테트라": "Tetra",
    "엘리시온": "Elysion",
    "미실리스": "Missilis",
    "필그림": "Pilgrim",
}

def translate_name(name):
    """Traduit le nom de la carte en anglais"""
    if name in card_name_translations:
        return card_name_translations[name]
    # Si pas de traduction exacte, on garde le nom original
    return name

def fix_effect(effect):
    """Remplace '트래시' par 'discard' et autres termes"""
    if not effect:
        return effect
    
    fixed = effect
    # Remplacer trash par discard
    fixed = fixed.replace("트래시", "discard")
    fixed = fixed.replace("트래시 존", "discard zone")
    
    return fixed

def process_cards():
    # Lire le fichier JSON
    with open('/workspace/cards.json', 'r', encoding='utf-8') as f:
        cards = json.load(f)
    
    # Traiter chaque carte
    for card in cards:
        # Traduire le nom
        if 'name' in card:
            card['name'] = translate_name(card['name'])
        
        # Fixer les effets (trash -> discard)
        if 'effect' in card:
            card['effect'] = fix_effect(card['effect'])
    
    # Sauvegarder le résultat
    with open('/workspace/cards_translated_en.json', 'w', encoding='utf-8') as f:
        json.dump(cards, f, ensure_ascii=False, indent=2)
    
    print(f"Traitement terminé! {len(cards)} cartes traitées.")
    print("Fichier sauvegardé: cards_translated_en.json")

if __name__ == "__main__":
    process_cards()
