#!/usr/bin/env python3
import json
import re

# Dictionnaire de traduction des noms de cartes
CARD_NAME_TRANSLATIONS = {
    "목단 - 화중지왕": "Peony - King of Flowers",
    "크라운 - 영화": "Crown - Movie",
    "프리바티 - 샤프 레슨": "Privaty - Sharp Lesson",
    "홍련 : 흑영 - 연화": "Hongryun : Black Shadow - Lotus Flower",
    "신데렐라": "Cinderella",
    "레드 후드": "Red Hood",
    "라피": "Rapi",
    "아니스": "Anis",
    "니언": "Nian",
    "노이즈": "Noise",
    "도라": "Dora",
    "루피": "Rupee",
    "티아": "Tia",
    "라푼젤": "Rapunzel",
    "길티": "Guilty",
    "디젤": "Diesel",
    "스노우 화이트": "Snow White",
    "백조": "Swan",
    "로산나": "Rosanna",
    "모더니아": "Modernia",
    "그레이브": "Grave",
    "헬름": "Helm",
    "크라운": "Crown",
    "나가": "Naga",
    "신": "Shin",
    "마스트": "Mast",
    "리틀 머메이드": "Little Mermaid",
    "도로시": "Dorothy",
    "루드밀라": "Ludmilla",
    "소다": "Soda",
    "일레그": "iLeg",
    "슈가": "Sugar",
    "맥스웰": "Maxwell",
    "비스킷": "Biscuit",
    "코코아": "Cocoa",
    "밀크": "Milk",
    "프림": "Prim",
    "레오나": "Leona",
    "네로": "Nero",
    "페퍼": "Pepper",
    "루마니": "Rumani",
    "아인": "Ein",
    "메어리": "Mary",
    "츠바이": "Zwei",
    "폴리": "Poly",
    "이사벨": "Isabel",
    "에피넬": "Epinel",
    "키리": "Kiri",
    "네베": "Neve",
    "팬텀": "Phantom",
    "볼륨": "Volume",
    "엠마": "Emma",
    "글레링 아이즈": "Glaring Eyes",
    "마르차나": "Marchana",
    "메이든": "Maiden",
    "클레이": "Clay",
    "베이": "Bay",
    "아리아": "Aria",
    "자칼": "Jackal",
    "누아르": "Noir",
    "블랑": "Blanc",
    "와일드 투스": "Wild Tooth",
    "벨로타": "Belorta",
    "미카": "Mica",
    "앤": "Anne",
    "솔린": "Soline",
    "퀀시": "Quency",
    "얀": "Yan",
    "브리드": "Brid",
    "에테르": "Ether",
    "미하라": "Miho",
    "시그널": "Signal",
    "애드미": "Admi",
    "사쿠라": "Sakura",
    "유니": "Uni",
    "엑시아": "Exia",
    "율하": "Yulha",
    "노벨": "Novel",
    "목단": "Peony",
    "길로틴": "Guillotine",
    "니힐리스타": "Nihilista",
    "트리나": "Trina",
    "플로라": "Flora",
    "율리아": "Yulia",
    "베스티": "Besty",
    "크러스트": "Crust",
    "브래디": "Brady",
    "하란": "Harran",
    "앵커": "Anchor",
    "폴크방": "Folkvang",
    "트라토리아": "Trattoria",
    "마틸다": "Matilda",
    "849": "849",
    "777": "777",
    "마리드": "Marid",
    "에셀": "Ethel",
    "아마릴리스": "Amaryllis",
    "디아블로": "Diablo",
    "페로로": "Peroro",
    "아야": "Aya",
    "메리": "Merri",
    "미스터": "Mr.",
    "엘브": "Elve",
    "아일랜드": "Island",
    "브레이드": "Blade",
    "에이프": "Ape",
    "카메오": "Cameo",
    "클로버": "Clover",
    "마리": "Mari",
    "비트": "Bit",
    "오로라": "Aurora",
    "레이디": "Lady",
    "앨리스": "Alice",
    "린네": "Linne",
    "에이다": "Ada",
    "미리카": "Mirika",
    "클레오": "Cleo",
    "파우더": "Powder",
    "마카롱": "Macaron",
    "쇼콜라": "Chocolat",
    "크림": "Cream",
    "젤리": "Jelly",
    "푸딩": "Pudding",
    "쿠키": "Cookie",
    "캔디": "Candy",
    "도넛": "Donut",
    "케이크": "Cake",
    "아이스": "Ice",
    "워터": "Water",
    "파이어": "Fire",
    "윈드": "Wind",
    "어스": "Earth",
    "라이트": "Light",
    "다크": "Dark",
    "홀리": "Holy",
    "섀도우": "Shadow",
    "블레이드": "Blade",
    "건너": "Gunner",
    "러셔": "Rusher",
    "서포터": "Supporter",
    "디펜더": "Defender",
    "어태커": "Attacker",
    "스나이퍼": "Sniper",
    "로켓": "Rocket",
    "미사일": "Missile",
    "봄": "Bomb",
    "그레네이드": "Grenade",
    "샷건": "Shotgun",
    "라이플": "Rifle",
    "피스톨": "Pistol",
    "개틀링": "Gatling",
    "체인건": "Chain Gun",
    "미니건": "Minigun",
    "캐논": "Cannon",
    "레일건": "Railgun",
    "플라스마": "Plasma",
    "레이저": "Laser",
    "빔": "Beam",
    "파동": "Wave",
    "충격": "Shock",
    "폭발": "Explosion",
    "연기": "Smoke",
    "불꽃": "Flame",
    "얼음": "Ice",
    "번개": "Lightning",
    "바람": "Wind",
    "흙": "Earth",
    "빛": "Light",
    "어둠": "Darkness",
    "성스러운": "Holy",
    "그림자": "Shadow",
    "검은": "Black",
    "흰색": "White",
    "붉은": "Red",
    "푸른": "Blue",
    "초록": "Green",
    "노란": "Yellow",
    "보라": "Purple",
    "핑크": "Pink",
    "주황": "Orange",
    "금색": "Gold",
    "은색": "Silver",
    "청동": "Bronze",
    "강철": "Steel",
    "다이아몬드": "Diamond",
    "루비": "Ruby",
    "사파이어": "Sapphire",
    "에메랄드": "Emerald",
    "토파즈": "Topaz",
    "오팔": "Opal",
    "진주": "Pearl",
    "산호": "Coral",
    "호박": "Amber",
    "수정": "Crystal",
    "유리": "Glass",
    "도자기": "Porcelain",
    "나무": "Wood",
    "돌": "Stone",
    "금속": "Metal",
    "천": "Cloth",
    "가죽": "Leather",
    "종이": "Paper",
    "플라스틱": "Plastic",
    "고무": "Rubber",
    "실리콘": "Silicon",
    "세라믹": "Ceramic",
    "타이탄": "Titan",
    "아틀라스": "Atlas",
    "갓데시움": "Goddessium",
    "노른": "Norn",
    "매터": "Matter",
    "패턴": "Pattern",
    "코드": "Code",
    "시크릿": "Secret",
    "히든": "Hidden",
    "클래식": "Classic",
    "모던": "Modern",
    "레트로": "Retro",
    "퓨처": "Future",
    "사이버": "Cyber",
    "스팀": "Steam",
    "디젤": "Diesel",
    "전기": "Electric",
    "태양": "Solar",
    "달": "Moon",
    "별": "Star",
    "우주": "Space",
    "갤럭시": "Galaxy",
    "네뷸라": "Nebula",
    "퀘이사": "Quasar",
    "펄서": "Pulsar",
    "블랙홀": "Black Hole",
    "웜홀": "Wormhole",
    "차원": "Dimension",
    "평행": "Parallel",
    "대체": "Alternate",
    "미래": "Future",
    "과거": "Past",
    "현재": "Present",
    "시간": "Time",
    "공간": "Space",
    "현실": "Reality",
    "환상": "Fantasy",
    "꿈": "Dream",
    "희망": "Hope",
    "절망": "Despair",
    "사랑": "Love",
    "증오": "Hatred",
    "분노": "Anger",
    "슬픔": "Sadness",
    "기쁨": "Joy",
    "행복": "Happiness",
    "불행": "Unhappiness",
    "운명": "Fate",
    "숙명": "Destiny",
    "인과": "Karma",
    "윤회": "Reincarnation",
    "부활": "Resurrection",
    "재생": "Regeneration",
    "치유": "Healing",
    "보호": "Protection",
    "방어": "Defense",
    "공격": "Attack",
    "지원": "Support",
    "강화": "Enhancement",
    "약화": "Weakening",
    "변형": "Transformation",
    "진화": "Evolution",
    "돌연변이": "Mutation",
    "적응": "Adaptation",
    "학습": "Learning",
    "성장": "Growth",
    "발전": "Development",
    "진보": "Progress",
    "퇴보": "Regression",
    "붕괴": "Collapse",
    "파괴": "Destruction",
    "창조": "Creation",
    "탄생": "Birth",
    "죽음": "Death",
    "생명": "Life",
    "영혼": "Soul",
    "정신": "Mind",
    "육체": "Body",
    "심장": "Heart",
    "뇌": "Brain",
    "눈": "Eye",
    "귀": "Ear",
    "입": "Mouth",
    "손": "Hand",
    "발": "Foot",
    "머리": "Head",
    "몸": "Body",
    "팔": "Arm",
    "다리": "Leg",
    "등": "Back",
    "배": "Stomach",
    "가슴": "Chest",
    "어깨": "Shoulder",
    "목": "Neck",
    "얼굴": "Face",
    "피부": "Skin",
    "뼈": "Bone",
    "근육": "Muscle",
    "혈액": "Blood",
    "신경": "Nerve",
    "세포": "Cell",
    "유전자": "Gene",
    "단백질": "Protein",
    "효소": "Enzyme",
    "호르몬": "Hormone",
    "면역": "Immunity",
    "바이러스": "Virus",
    "박테리아": "Bacteria",
    "감염": "Infection",
    "질병": "Disease",
    "치료": "Treatment",
    "약": "Medicine",
    "독": "Poison",
    "해독": "Antidote",
    "백신": "Vaccine",
    "항체": "Antibody",
    "항원": "Antigen",
    "알레르기": "Allergy",
    "염증": "Inflammation",
    "통증": "Pain",
    "마취": "Anesthesia",
    "수술": "Surgery",
    "이식": "Transplant",
    "재활": "Rehabilitation",
    "요양": "Nursing",
    "간호": "Care",
    "복지": "Welfare",
    "안전": "Safety",
    "위험": "Danger",
    "사고": "Accident",
    "재난": "Disaster",
    "재해": "Calamity",
    "전쟁": "War",
    "전투": "Battle",
    "싸움": "Fight",
    "승리": "Victory",
    "패배": "Defeat",
    "평화": "Peace",
    "갈등": "Conflict",
    "협상": "Negotiation",
    "외교": "Diplomacy",
    "동맹": "Alliance",
    "적대": "Hostility",
    "경쟁": "Competition",
    "협력": "Cooperation",
    "팀워크": "Teamwork",
    "리더십": "Leadership",
    "팔로우": "Followership",
    "권한": "Authority",
    "책임": "Responsibility",
    "의무": "Duty",
    "권리": "Right",
    "자유": "Freedom",
    "평등": "Equality",
    "정의": "Justice",
    "불의": "Injustice",
    "법률": "Law",
    "규칙": "Rule",
    "규정": "Regulation",
    "정책": "Policy",
    "제도": "System",
    "조직": "Organization",
    "기관": "Institution",
    "회사": "Company",
    "기업": "Corporation",
    "정부": "Government",
    "국가": "Nation",
    "사회": "Society",
    "공동체": "Community",
    "가족": "Family",
    "친구": "Friend",
    "동료": "Colleague",
    "동반자": "Companion",
    "파트너": "Partner",
    "ライバル": "Rival",
    "적": "Enemy",
    "아군": "Ally",
    "중립": "Neutral",
    "우호": "Friendly",
    "적대적": "Hostile",
    "선한": "Good",
    "악한": "Evil",
    "중립적": "Neutral",
    "질서": "Order",
    "혼돈": "Chaos",
    "균형": "Balance",
    "조화": "Harmony",
    "불균형": "Imbalance",
    "不调和": "Discord",
    "통일": "Unity",
    "분열": "Division",
    "통합": "Integration",
    "분리": "Separation",
    "결합": "Combination",
    "분해": "Decomposition",
    "합성": "Synthesis",
    "분석": "Analysis",
    "종합": "Synthesis",
    "귀납": "Induction",
    "연역": "Deduction",
    "추론": "Reasoning",
    "논리": "Logic",
    "직관": "Intuition",
    "감각": "Sense",
    "지각": "Perception",
    "인지": "Cognition",
    "이해": "Understanding",
    "파악": "Grasp",
    "판단": "Judgment",
    "결정": "Decision",
    "선택": "Choice",
    "선호": "Preference",
    "욕구": "Desire",
    "욕망": "Desire",
    "필요": "Need",
    "원함": "Want",
    "목표": "Goal",
    "목적": "Purpose",
    "의미": "Meaning",
    "가치": "Value",
    "중요성": "Importance",
    "우선순위": "Priority",
    "전략": "Strategy",
    "전술": "Tactics",
    "계획": "Plan",
    "준비": "Preparation",
    "실행": "Execution",
    "평가": "Evaluation",
    "피드백": "Feedback",
    "개선": "Improvement",
    "혁신": "Innovation",
    "발명": "Invention",
    "발견": "Discovery",
    "탐색": "Exploration",
    "연구": "Research",
    "조사": "Investigation",
    "실험": "Experiment",
    "관찰": "Observation",
    "측정": "Measurement",
    "계산": "Calculation",
    "예측": "Prediction",
    "예상": "Expectation",
    "추정": "Estimation",
    "가설": "Hypothesis",
    "이론": "Theory",
    "법칙": "Law",
    "원리": "Principle",
    "규칙": "Rule",
    "패턴": "Pattern",
    "구조": "Structure",
    "기능": "Function",
    "역할": "Role",
    "위치": "Position",
    "상태": "State",
    "조건": "Condition",
    "상황": "Situation",
    "환경": "Environment",
    "맥락": "Context",
    "배경": "Background",
    "역사": "History",
    "문화": "Culture",
    "전통": "Tradition",
    "관습": "Custom",
    "습관": "Habit",
    "매너": "Manner",
    "에티켓": "Etiquette",
    "도덕": "Morality",
    "윤리": "Ethics",
    "양심": "Conscience",
    "신념": "Belief",
    "신앙": "Faith",
    "종교": "Religion",
    "철학": "Philosophy",
    "사상": "Ideology",
    "세계관": "Worldview",
    "가치관": "Values",
    "人生觀": "Outlook on Life",
    "死生觀": "View on Death",
    "자연": "Nature",
    "인간": "Human",
    "동물": "Animal",
    "식물": "Plant",
    "광물": "Mineral",
    "기후": "Climate",
    "날씨": "Weather",
    "계절": "Season",
    "봄": "Spring",
    "여름": "Summer",
    "가을": "Autumn",
    "겨울": "Winter",
    "아침": "Morning",
    "점심": "Noon",
    "저녁": "Evening",
    "밤": "Night",
    "오늘": "Today",
    "내일": "Tomorrow",
    "어제": "Yesterday",
    "지금": "Now",
    "나중": "Later",
    "이전에": "Before",
    "이후에": "After",
    "동안": "During",
    "까지": "Until",
    "부터": "From",
    "사이": "Between",
    "among": "Among",
    "위": "Above",
    "아래": "Below",
    "앞": "Front",
    "뒤": "Back",
    "왼쪽": "Left",
    "오른쪽": "Right",
    "안": "Inside",
    "밖": "Outside",
    "옆": "Side",
    "가운데": "Center",
    "끝": "End",
    "시작": "Start",
    "중간": "Middle",
    "전체": "Whole",
    "부분": "Part",
    "일부": "Some",
    "모두": "All",
    "없음": "None",
    "있음": "Existence",
    "부재": "Absence",
    "존재": "Being",
    "비존재": "Non-being",
    "실체": "Entity",
    "본질": "Essence",
    "현상": "Phenomenon",
    "외관": "Appearance",
    "내면": "Interior",
    "표면": "Surface",
    "깊이": "Depth",
    "높이": "Height",
    "너비": "Width",
    "길이": "Length",
    "크기": "Size",
    "형태": "Shape",
    "색깔": "Color",
    "질감": "Texture",
    "냄새": "Smell",
    "맛": "Taste",
    "소리": "Sound",
    "빛": "Light",
    "그림자": "Shadow",
    "반사": "Reflection",
    "굴절": "Refraction",
    "흡수": "Absorption",
    "방출": "Emission",
    "전달": "Transmission",
    "전도": "Conduction",
    "대류": "Convection",
    "복사": "Radiation",
    "에너지": "Energy",
    "힘": "Force",
    "운동": "Motion",
    "속도": "Velocity",
    "가속도": "Acceleration",
    "질량": "Mass",
    "무게": "Weight",
    "밀도": "Density",
    "압력": "Pressure",
    "온도": "Temperature",
    "열": "Heat",
    "냉기": "Cold",
    "습도": "Humidity",
    "건조": "Dryness",
    "젖음": "Wetness",
    "마름": "Dryness",
    "부드러움": "Softness",
    "딱딱함": "Hardness",
    "유연함": "Flexibility",
    "강성": "Stiffness",
    "탄성": "Elasticity",
    "소성": "Plasticity",
    "취성": "Brittleness",
    "인성": "Toughness",
    "강도": "Strength",
    "내구성": "Durability",
    "내마모성": "Wear Resistance",
    "내식성": "Corrosion Resistance",
    "내열성": "Heat Resistance",
    "내한성": "Cold Resistance",
    "내약품성": "Chemical Resistance",
    "절연성": "Insulation",
    "전도성": "Conductivity",
    "자성": "Magnetism",
    "전기": "Electricity",
    "전자": "Electron",
    "양성자": "Proton",
    "중성자": "Neutron",
    "원자": "Atom",
    "분자": "Molecule",
    "이온": "Ion",
    "화학": "Chemistry",
    "물리": "Physics",
    "생물": "Biology",
    "수학": "Mathematics",
    "기하": "Geometry",
    "대수": "Algebra",
    "미적분": "Calculus",
    "통계": "Statistics",
    "확률": "Probability",
    "논리": "Logic",
    "컴퓨터": "Computer",
    "소프트웨어": "Software",
    "하드웨어": "Hardware",
    "네트워크": "Network",
    "인터넷": "Internet",
    "웹": "Web",
    "앱": "App",
    "프로그램": "Program",
    "데이터": "Data",
    "정보": "Information",
    "지식": "Knowledge",
    "지혜": "Wisdom",
    "기술": "Technology",
    "과학": "Science",
    "공학": "Engineering",
    "의학": "Medicine",
    "법학": "Law",
    "경제학": "Economics",
    "경영학": "Business",
    "회계": "Accounting",
    "금융": "Finance",
    "마케팅": "Marketing",
    "광고": "Advertising",
    "판매": "Sales",
    "구매": "Purchase",
    "소비": "Consumption",
    "생산": "Production",
    "유통": "Distribution",
    "물류": "Logistics",
    "공급": "Supply",
    "수요": "Demand",
    "시장": "Market",
    "가격": "Price",
    "비용": "Cost",
    "이익": "Profit",
    "손실": "Loss",
    "투자": "Investment",
    "저축": "Savings",
    "대출": "Loan",
    "이자": "Interest",
    "보험": "Insurance",
    "세금": "Tax",
    "예산": "Budget",
    "자산": "Asset",
    "부채": "Liability",
    "자본": "Capital",
    "주식": "Stock",
    "채권": "Bond",
    "펀드": "Fund",
    "파생상품": "Derivative",
    "선물": "Future",
    "옵션": "Option",
    "스왑": "Swap",
    "환율": "Exchange Rate",
    "인플레이션": "Inflation",
    "디플레이션": "Deflation",
    "경기": "Economy",
    "호황": "Boom",
    "불황": "Recession",
    "공황": "Panic",
    "위기": "Crisis",
    "기회": "Opportunity",
    "위험": "Risk",
    "불확실성": "Uncertainty",
    "변동성": "Volatility",
    "안정성": "Stability",
    "성장": "Growth",
    "발전": "Development",
    "진보": "Progress",
    "혁신": "Innovation",
    "창의성": "Creativity",
    " 상상력": "Imagination",
    "영감": "Inspiration",
    "동기": "Motivation",
    "열정": "Passion",
    "헌신": "Dedication",
    "끈기": "Perseverance",
    "인내": "Patience",
    "용기": "Courage",
    "두려움": "Fear",
    "걱정": "Worry",
    "스트레스": "Stress",
    "불안": "Anxiety",
    "공포": "Terror",
    "놀라움": "Surprise",
    "흥미": "Interest",
    "호기심": "Curiosity",
    "주의": "Attention",
    "집중": "Concentration",
    "기억": "Memory",
    "학습": "Learning",
    "교육": "Education",
    "훈련": "Training",
    "연습": "Practice",
    "숙련": "Skill",
    "전문성": "Expertise",
    "능력": "Ability",
    "재능": "Talent",
    "천재성": "Genius",
    "지능": "Intelligence",
    "IQ": "IQ",
    "EQ": "EQ",
    "AQ": "AQ",
    "성격": "Personality",
    "기질": "Temperament",
    "성향": "Disposition",
    "특징": "Characteristic",
    "특질": "Trait",
    "스타일": "Style",
    "유행": "Fashion",
    "트렌드": "Trend",
    "유행": "Trend",
    "인기": "Popularity",
    "명성": "Reputation",
    "이미지": "Image",
    "브랜드": "Brand",
    "アイ덴티티": "Identity",
    "자기": "Self",
    "타인": "Others",
    "관계": "Relationship",
    "소통": "Communication",
    "대화": "Conversation",
    "언어": "Language",
    "말": "Speech",
    "글": "Writing",
    "문자": "Character",
    "기호": "Symbol",
    "의미": "Meaning",
    "내용": "Content",
    "형식": "Form",
    "구조": "Structure",
    "시스템": "System",
    "프로세스": "Process",
    "절차": "Procedure",
    "방법": "Method",
    "방식": "Way",
    "기술": "Technique",
    "전략": "Strategy",
    "접근": "Approach",
    "모델": "Model",
    "프레임워크": "Framework",
    "패러다임": "Paradigm",
    "이론": "Theory",
    "개념": "Concept",
    "아이디어": "Idea",
    "생각": "Thought",
    "의견": "Opinion",
    "견해": "View",
    "관점": "Perspective",
    "시각": "Viewpoint",
    "입장": "Position",
    "태도": "Attitude",
    "행동": "Behavior",
    "활동": "Activity",
    "작용": "Action",
    "반응": "Reaction",
    "상호작용": "Interaction",
    "영향": "Influence",
    "효과": "Effect",
    "결과": "Result",
    "성과": "Outcome",
    "성공": "Success",
    "실패": "Failure",
    "도전": "Challenge",
    "장애물": "Obstacle",
    "문제": "Problem",
    "해결": "Solution",
    "답": "Answer",
    "질문": "Question",
    "의문": "Doubt",
    "확신": "Certainty",
    "의심": "Doubt",
    "신뢰": "Trust",
    "의심": "Distrust",
    "충성": "Loyalty",
    "배신": "Betrayal",
    "약속": "Promise",
    "계약": "Contract",
    "합의": "Agreement",
    "동의": "Consent",
    "거부": "Refusal",
    "승인": "Approval",
    "허가": "Permission",
    "금지": "Prohibition",
    "제한": "Restriction",
    "규제": "Regulation",
    "통제": "Control",
    "관리": "Management",
    "운영": "Operation",
    "유지": "Maintenance",
    "보수": "Repair",
    "점검": "Inspection",
    "감사": "Audit",
    "평가": "Evaluation",
    "심사": "Review",
    "검사": "Examination",
    "테스트": "Test",
    "인증": "Certification",
    "인가": "Authorization",
    "등록": "Registration",
    "신고": "Report",
    "신청": "Application",
    "접수": "Receipt",
    "처리": "Processing",
    "완료": "Completion",
    "종료": "Termination",
    "시작": "Start",
    "개시": "Initiation",
    "개봉": "Opening",
    "폐쇄": "Closing",
    "잠금": "Lock",
    "해제": "Unlock",
    "보안": "Security",
    "안전": "Safety",
    "위험": "Danger",
    "경고": "Warning",
    "주의": "Caution",
    "예방": "Prevention",
    "대비": "Preparation",
    "응급": "Emergency",
    "구조": "Rescue",
    "구호": "Relief",
    "복구": "Recovery",
    "복원": "Restoration",
    "재건": "Reconstruction",
    "재생": "Regeneration",
    "갱신": "Renewal",
    "업데이트": "Update",
    "업그레이드": "Upgrade",
    "다운그레이드": "Downgrade",
    "롤백": "Rollback",
    "백업": "Backup",
    "복원": "Restore",
    "동기화": "Synchronization",
    "암호화": "Encryption",
    "복호화": "Decryption",
    "인증": "Authentication",
    "인가": "Authorization",
    "접근": "Access",
    "권한": "Permission",
    "로그인": "Login",
    "로그아웃": "Logout",
    "가입": "Sign up",
    "탈퇴": "Withdrawal",
    "구독": "Subscription",
    "해지": "Cancellation",
    "결제": "Payment",
    "환불": "Refund",
    "영수증": "Receipt",
    "송장": "Invoice",
    "명세서": "Statement",
    "보고서": "Report",
    "문서": "Document",
    "파일": "File",
    "폴더": "Folder",
    "디렉토리": "Directory",
    "데이터베이스": "Database",
    "서버": "Server",
    "클라이언트": "Client",
    "API": "API",
    "SDK": "SDK",
    "라이브러리": "Library",
    "프레임워크": "Framework",
    "플랫폼": "Platform",
    "인프라": "Infrastructure",
    "클라우드": "Cloud",
    "온프레미스": "On-premise",
    "하이브리드": "Hybrid",
    "멀티": "Multi",
    "싱글": "Single",
    "듀얼": "Dual",
    "트리플": "Triple",
    "쿼드": "Quad",
    "옥토": "Octo",
    "데카": "Deca",
    "헥사": "Hexa",
    "펜타": "Penta",
    "테트라": "Tetra",
    "트라이": "Tri",
    "바이": "Bi",
    "모노": "Mono",
    "유니": "Uni",
    "올리": "All",
    "팬": "Pan",
    "프로": "Pro",
    "콘": "Con",
    "contra": "Contra",
    "안티": "Anti",
    "논": "Non",
    "인": "In",
    "아웃": "Out",
    "업": "Up",
    "다운": "Down",
    "오버": "Over",
    "언더": "Under",
    "슈퍼": "Super",
    "서브": "Sub",
    "하이퍼": "Hyper",
    "메타": "Meta",
    "트랜스": "Trans",
    "인터": "Inter",
    "인트라": "Intra",
    "엑스트라": "Extra",
    "울트라": "Ultra",
    "기가": "Giga",
    "테라": "Tera",
    "페타": "Peta",
    "엑사": "Exa",
    "제타": "Zetta",
    "요타": "Yotta",
    "밀리": "Milli",
    "마이크로": "Micro",
    "나노": "Nano",
    "피코": "Pico",
    "펨토": "Femto",
    "아토": "Atto",
    "제프토": "Zepto",
    "욕토": "Yocto",
}

# Traductions supplémentaires pour les termes de jeu
GAME_TERM_TRANSLATIONS = {
    "트래시": "discard",
    "쓰레기": "discard", 
    "trash": "discard",
    "Deck card": "Deck card",
    "unit": "Unit",
    "Encounter": "When this unit encounters",
    "power": "power",
    "cost": "cost",
    "draw": "draw a card",
    "Sacrifice": "Sacrifice",
    "Finisher": "Finisher",
    "On the field": "On the field",
    "your units": "your units",
    "opponent's units": "opponent's units",
    "choose any number": "choose any number",
    "Until the end of this turn": "Until the end of this turn",
    "If you do": "If you do",
    "Then": "Then",
    "With this effect": "With this effect",
    "Equip": "Equip",
    "item": "item",
    "card": "card",
    "Leader": "Leader",
    "Unit": "Unit",
    "Skill": "Skill",
    "Item": "Item",
}

def translate_card_name(korean_name):
    """Traduit un nom de carte du coréen vers l'anglais"""
    # Vérifier d'abord dans le dictionnaire exact
    if korean_name in CARD_NAME_TRANSLATIONS:
        return CARD_NAME_TRANSLATIONS[korean_name]
    
    # Sinon, retourner le nom original (pourrait être déjà en anglais ou nécessiter une traduction manuelle)
    return korean_name

def clean_effect_text(effect):
    """Nettoie et améliore le texte des effets"""
    if not effect:
        return effect
    
    # Remplacer trash par discard
    effect = re.sub(r'\btrash\b', 'discard', effect, flags=re.IGNORECASE)
    
    # Corriger les espaces manquants
    effect = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', effect)  # "0cost" -> "0 cost"
    effect = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', effect)  # "cost0" -> "cost 0"
    effect = re.sub(r'([a-z])([A-Z])', r'\1 \2', effect)  # "discardIf" -> "discard If"
    
    # Améliorer la formulation
    effect = re.sub(r'choose any number of (discard it|discard them)', r'choose any number and \1', effect)
    
    return effect

def main():
    # Charger le fichier JSON
    with open('cards.json', 'r', encoding='utf-8') as f:
        cards = json.load(f)
    
    print(f"Chargement de {len(cards)} cartes...")
    
    # Traduire les cartes
    translated_count = 0
    for card in cards:
        # Traduire le nom
        old_name = card.get('name', '')
        new_name = translate_card_name(old_name)
        
        if old_name != new_name:
            card['name'] = new_name
            translated_count += 1
        
        # Nettoyer l'effet
        if 'effect' in card:
            old_effect = card['effect']
            new_effect = clean_effect_text(old_effect)
            if old_effect != new_effect:
                card['effect'] = new_effect
    
    print(f"{translated_count} noms traduits")
    
    # Sauvegarder le fichier traduit
    with open('cards_english.json', 'w', encoding='utf-8') as f:
        json.dump(cards, f, indent=2, ensure_ascii=False)
    
    print("Fichier sauvegardé: cards_english.json")
    
    # Vérifications
    with open('cards_english.json', 'r', encoding='utf-8') as f:
        check_cards = json.load(f)
    
    trash_count = sum(1 for card in check_cards if 'trash' in card.get('effect', '').lower())
    discard_count = sum(1 for card in check_cards if 'discard' in card.get('effect', '').lower())
    
    print(f"\nVérification:")
    print(f"- Occurrences de 'trash': {trash_count}")
    print(f"- Occurrences de 'discard': {discard_count}")

if __name__ == '__main__':
    main()
